# https://github.com/repository-settings/app
_extends: .github
repository:
  name: sanity-typed
  private: false
labels:
  - name: schema-builder
  - name: types
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - Build
          - Lint
          - Test
